In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("session4_dummy_students_data.csv")

print(df.head())
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())


#df["science"] = df["science"].fillna(df["science"].median())



   student_id   name  age     city  math  science  english  \
0         101  Aarav   16   Mumbai    78       84       69   
1         102   Diya   16    Delhi    91       88       94   
2         103  Kabir   17  Mathura    55       61       58   
3         104  Meera   16    Noida    72       79       81   
4         105  Rohan   17   Mumbai    40       52       47   

   attendance_percent  study_hours_per_week  assignments_submitted  \
0                  92                     8                      9   
1                  96                    11                     10   
2                  75                     5                      6   
3                  89                     7                      8   
4                  68                     3                      5   

   final_project_score  
0                   82  
1                   93  
2                   60  
3                   78  
4                   45  
Shape: (20, 11)
Columns: ['student_id', 'name', 'age', '

In [ ]:

['student_id', 'name', 'age', 'city', 'math', 'science', 'english', 'attendance_percent', 'study_hours_per_week', 'assignments_submitted', 'final_project_score']

#identifier-student_id
#categories-
#measurable values


In [4]:
#numy complettion

#parameters

def calculate_average(values):
  if len(values)==0:
    return None
  return sum(values)/len(values)

scores= []
result= calculate_average(scores)
print(result)


ZeroDivisionError: division by zero

In [5]:
#python list can handle

math_scores= df["math"].to_numpy()

print(math_scores)
print("Mean:", math_scores.mean())
print("Minimum:", math_scores.min())
print("Maximum:", math_scores.max())
print("Total:", math_scores.sum())


[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]
Mean: 69.5
Minimum: 35
Maximum: 95
Total: 1390


In [ ]:
#mean, min, max and sum for english and science

In [8]:
#python list can handle

science_scores= df["science"].to_numpy()

print(science_scores)
print("Mean:", science_scores.mean())
print("Minimum:", science_scores.min())
print("Maximum:", science_scores.max())
print("Total:", science_scores.sum())


[84 88 61 79 52 93 70 92 57 76 63 81 45 86 54 90 69 85 49 73]
Mean: 72.35
Minimum: 45
Maximum: 93
Total: 1447


In [12]:
print(math_scores > 75)
print(math_scores[math_scores > 75])
print("Count above 75:", (math_scores > 75).sum())


[ True  True False False False  True False  True False  True False False
 False  True False  True False  True False  True]
[78 91 88 95 83 89 92 80 77]
Count above 75: 9


In [ ]:
#convert the english column into numpy,print mean, lowest, highest, print the number of scores greater than or equal to 80
#dont use loops

In [13]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   student_id             20 non-null     int64 
 1   name                   20 non-null     object
 2   age                    20 non-null     int64 
 3   city                   20 non-null     object
 4   math                   20 non-null     int64 
 5   science                20 non-null     int64 
 6   english                20 non-null     int64 
 7   attendance_percent     20 non-null     int64 
 8   study_hours_per_week   20 non-null     int64 
 9   assignments_submitted  20 non-null     int64 
 10  final_project_score    20 non-null     int64 
dtypes: int64(9), object(2)
memory usage: 1.8+ KB
None


In [14]:
print(df.dtypes)

student_id                int64
name                     object
age                       int64
city                     object
math                      int64
science                   int64
english                   int64
attendance_percent        int64
study_hours_per_week      int64
assignments_submitted     int64
final_project_score       int64
dtype: object


In [16]:
#column cleanup

df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(r"[^a-z0-9]+", "_", regex=True)
      .str.strip("_")
)

print(df.columns.tolist())


['student_id', 'name', 'age', 'city', 'math', 'science', 'english', 'attendance_percent', 'study_hours_per_week', 'assignments_submitted', 'final_project_score']


In [17]:
df["student_id"]=df["student_id"].astype("string")
df["city"]=df["city"].astype("category")

In [18]:
#MISSING VALUES

missing_demo = df.copy()

missing_demo.loc[2, "science"] = np.nan
missing_demo.loc[8, "attendance_percent"] = np.nan
missing_demo.loc[14, "city"] = None

print(missing_demo.isna().sum())


student_id               0
name                     0
age                      0
city                     1
math                     0
science                  1
english                  0
attendance_percent       1
study_hours_per_week     0
assignments_submitted    0
final_project_score      0
dtype: int64


In [ ]:
science_median= missing_demo["science"].median()
attendance_median = missing_demo["attendance_percent"].median()
city_mode= missing_demo["city"].mode()[0]


missing_demo["science"] = missing_demo["science"].fillna(science_median)


In [19]:
#create a copy named practice_df. Make the math value in the row 0 missing. Print the missing count, fill the missing math value with math median
#print the missing value

practice_df = df.copy()
practice_df.loc[0, "math"] = np.nan
print(practice_df.isna().sum())

In [20]:
#averages and some basic summaries
#derive a new column (feature creation) for each student we will calculate their subject averages

df["average_score"]= (
    df[["math", "science", "english"]]
    .mean(axis=1)
    .round(2)
)

print(df[["name","math","science","english","average_score"]].head())



    name  math  science  english  average_score
0  Aarav    78       84       69          77.00
1   Diya    91       88       94          91.00
2  Kabir    55       61       58          58.00
3  Meera    72       79       81          77.33
4  Rohan    40       52       47          46.33


In [22]:
print("Class average:", df["average_score"].mean())
print("Lowest average:", df["average_score"].min())
print("Highest average:", df["average_score"].max())
print("Students:", df["student_id"].count())

print(df['average_score'].describe())

Class average: 71.35000000000001
Lowest average: 40.67
Highest average: 92.67
Students: 20
count    20.000000
mean     71.350000
std      16.753219
min      40.670000
25%      57.832500
50%      76.835000
75%      84.170000
max      92.670000
Name: average_score, dtype: float64


In [24]:
#count mean, minumum and max

#loc means label based indexing
top_student = df.loc[df["average_score"].idxmax(), ["name", "average_score"]]
print(top_student)

low_attendance= df[df["attendance_percent"]<75]
print(low_attendance[["name", "attendance_percent", "average_score"]])
#

name              Riya
average_score    92.67
Name: 15, dtype: object
      name  attendance_percent  average_score
4    Rohan                  68          46.33
8   Vivaan                  71          52.00
12     Dev                  62          40.67
18    Yash                  66          46.00


In [ ]:
#GROUP the data
#by same city

#by top 25 np.percentile


#based on these groups, identify some insights